### ISSUE TITLE
Typos in README and 01_pingTheAPI

### ISSUE THREAD

**Issue by MaikNog** [DannyDainton/All-Things-Postman#1]
**README.md**
fimialir => familiar
platfrom => platform

**01_pingTheAPI.md**
potentail => potential

(Couldn't submit a PR)

**Comment by DannyDainton** [comment]
Cheers! Have have no doubt that there will be more...I need to defocus more :)

**Comment by DannyDainton** [comment]
Fixed those plus a couple more that you missed ;)
