### ISSUE TITLE
Type in Example 10

### ISSUE THREAD

**Issue by rob212** [DannyDainton/All-Things-Postman#4]
I have found a minor typo in Example 10 - create new bookings via POST. 

At the end of the article when referring to the upcoming example it is stated:
"In the **nest** example we will be looking..." 

instead of the presumably intended:
"In the **next** example we will be looking..." 

Great resource, thanks for sharing.

**Comment by DannyDainton** [comment]
Oh dear... Thanks for pointing that out. I'll fix that now 😁
