### ISSUE TITLE
A question about compressing request body

### ISSUE THREAD

**Issue by ChrisHAdams** [DannyDainton/All-Things-Postman#6]
Hi,

I have an API whereby the body of a POST request needs to be compressed prior to sending or rather the API expects a compressed body.

The API is written in Node and the front-end is written in React.  The API is used for product searching.  E.g. submit a list of barcodes and then the response contains how much product of each barcode we have.

The reason for compressing the payload is that the request list can be in the tens of thousands and the (compressed) results can be in the hundreds of thousands.

My usual API testing tool is SoapUI and I can set SoapUI to auto-compress the body and then inflate the response.

I'm trying to learn Postman, but I can't see how to compress the payload.  There doesn't seem to be an 'out of the box' solution to this.

The only other option I can think of would be to use the pre-request script, but I don't see how I can import zlib for handling the compression.  If I could do that, I could 'push' the compressed body value into the request step.

I did find this [GitHub issue](https://github.com/postmanlabs/postman-app-support/issues/4079) but it doesn't help.

I'd be grateful if you could make any suggestions.

**Comment by DannyDainton** [comment]
Hey @ChrisHAdams

Is that changing one of the Headers in someway to force the compression? 

Just trying to understand the usecase a little more to provide a better answer. 

I'll also have a quick chat with the team about this, it's not something that I know a great deal about but hopefully they can give me some pointers.

**Comment by ChrisHAdams** [comment]
Hi,

Re “Is that changing one of the Headers in someway to force the compression?”.  If you mean in SoapUI, you have to set the headers, but that doesn’t trigger compression. To make the body compressed, you have to set it in the preferences.  Which is annoying when you switch to another workspace which doesn’t require compression and then your tests fail!

**Comment by DannyDainton** [comment]
I get that it's a preference setting but internally, it must doing something to set the compression for the request.

Do you have an example of the request Headers for both compressed and non compressed requests?

**Comment by ChrisHAdams** [comment]
Hi,

Sorry Danny, yes, you need to see the headers.  Please see below.

**Uncompressed SoapUI Headers**

`
POST https://someDomain/app/api/search/ HTTP/1.1
Accept-Encoding: gzip,deflate
Content-Type: application/json;charset=UTF-8
Content-Length: 143
Host: someDomain
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.1.1 (java 1.5)
`


**Compressed SoapUI Headers**

Then, after setting the 'Request compression' to gzip in SoapUI properties, the request headers look like...

`
POST https://someDomain/app/api/search/ HTTP/1.1
Content-Encoding: gzip
Accept-Encoding: gzip,deflate
Content-Type: application/json;charset=UTF-8
Content-Length: 128
Host: someDomain
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.1.1 (java 1.5)
`

The difference is the Content-Encoding header parameter.  When you click 'Send', SoapUI then does the compression prior to sending and using the 'Raw' tab which shows exactly what SoapUI sent, you can seen the body has been compressed by the non-readable chars.

**Comment by DannyDainton** [comment]
Going to close this issue @ChrisHAdams - I'm not sure I can help here but feel free to raise the question on the [Postman Community Site](https://community.getpostman.com/) or an Issue on the [Postman GH Repo](https://github.com/postmanlabs/postman-app-support/issues).
