### ISSUE TITLE
Newman html extra report is not generated

### ISSUE THREAD

**Issue by Pradeep07-max** [DannyDainton/All-Things-Postman#7]
Using Newman CMD for generating a response report. 
My scenario is I have JSON data driven testing file using registered for multiple companies.i have environmental variables also in global. 

CMD is ,  > newnan run collection.json -d ddt.json -n16 -e globalVariableCollection.json - r htmlextra

**Comment by Pradeep07-max** [comment]
@DannyDainton , when i used this CMD its working. 
 >>  newman run RegisterCompany.json -d companyjsonforregistration.json -n 16 -e MyWorkspace.postman_globals.json -r htmlextra --reporter-htmlextra-export example1.html.

but this cmd is not working . its shows size o file.

>> newman run RegisterCompany.json -d companyjsonforregistration.json -n 16 -e MyWorkspace.postman_globals.json -r htmlextra --reporter-htmlextra-title "Registration Company API Test Reoprt"

another thing i want to use custom title with custom file name is any possible way .

**Comment by DannyDainton** [comment]
Can you move this issue the the htmlextra reporter please.

https://github.com/DannyDainton/newman-reporter-htmlextra/issues

There's a bug template on the repo, please fill in all the details with as much information as you can.
